### ISSUE TITLE
Split click callbacks in click and on change

### ISSUE THREAD

**Issue by melonora** [scverse/napari-spatialdata#103]
From my understanding most of the callbacks are being triggered by clicks instead of item changes. This would mean that programmatically if you change an item no callback is necessarily triggered. I think we have to discuss separating callbacks where the click callbacks would only change the row for example in a widget which then triggers another callback actually changing anything that is displayed. For example:

1. coordinate_system widget on click on another coordinate system change the current coordinate system.
2. on coordinate system change update layer visibility.

What do you think? I think this is also easier maintainable when writing tests as right now I believe we have to simulate mouseclicks every time.

**Comment by LucaMarconato** [comment]
I also think that on-change would be better than on-click, for instance this would allow to use the arrow keys (haven't tried but by reading this I understand that they won't work).
