### ISSUE TITLE
`Interactive()` requires `.run()` in `main` but not in `spatialdata` branch

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#108]
When calling `Interactive()` from the `spatialdata` branch, `napari.run()` is called internally. This doesn't happen in the current version of the `main` branch and can create confusion to the user (who would not see napari loading), as the notebooks where created with the `spatialdata` branch.

Todo:
~~- [ ] consider adding `napari.run()` inside interactive as I don't think there is a use case in keeping it separate.~~ Edit: keeping it separate but `Interactive.run()` is now called by default by the `__init__()`.
- [ ] (luca), put all the notebooks and tests of `spatialdata-sandbox` in an Airflow pipeline ran nightly to catch bugs like this (in `spatialdata-sandbox` there is a test against this with a headless version of napari).

**Comment by rahulbshrestha** [comment]
Hey @LucaMarconato, there is already a method for executing `napari.run()` inside the Interactive class.

https://github.com/scverse/napari-spatialdata/blob/291ede5d85de6026b92bda64094508a24f1b86f3/src/napari_spatialdata/_interactive.py#L292-L293

This way, in the notebooks, we execute the viewer by 
```
interactive = Interactive(sdata)
interactive.run()
```
Isn't this better than include it as part of the constructor of the `Interactive` class?

**Comment by LucaMarconato** [comment]
I would call it directly from the constructor. I would put an optional value to call interactive without calling run, but I think most of them time it would be handier to have it run automatically.
