### ISSUE TITLE
Give out of date with main branch warning

### ISSUE THREAD

**Issue by melonora** [scverse/napari-spatialdata#109]
Are people ok with enforcing this for pull requests?

**Comment by kevinyamauchi** [comment]
I am sorry, but I am not following. What do you mean?

**Comment by melonora** [comment]
@kevinyamauchi  This:
![afbeelding](https://github.com/scverse/napari-spatialdata/assets/22346363/9e40d70e-8b22-4ad1-88cd-83dca2ec45e7)

**Comment by kevinyamauchi** [comment]
As far as I understand it, that doesn't actually enforce anything, right? Isn't it just a reminder to merge main? I don't have a strong preference either way, so I've turned it on in case people find it helpful. We can revert if others don't agree.

**Comment by melonora** [comment]
I think in general it would be good policy. Yesterday with the doc build I pushed a bug fix. This doc build before the bug fix failed on every PR. One cannot necessarily be certain that after a bug fix is implemented that the code in several PRs will actually work and thus main has to be first merged in those branches. If there are no merge conflicts then this is just a very easy way to do it:) I think in the napari repo it actually blocks if the PR is not up to date with main but could be mistaken.
