### ISSUE TITLE
Can I get the mask with image, table and shape I draw manually using napari?

### ISSUE THREAD

**Issue by yedeer12** [scverse/napari-spatialdata#113]
I only have the image and table (MERSCOPE) and the shape I draw manually using napari. I would like to know if I can also get the mask like the data raccoon in the tutorial.

**Comment by melonora** [comment]
Hi @yedeer12, could you please provide a little bit more information? Would you like to have the shape displayed as a mask (labels layer)? Or is your question regarding how to add a label element?

**Comment by yedeer12** [comment]
> Hi @yedeer12, could you please provide a little bit more information? Would you like to have the shape displayed as a mask (labels layer)? Or is your question regarding how to add a label element?

The MERSCOPE data I have is anndata (table/metadata) and an original image. Then I get the polygon shape using Napari. Can I use the shape to aggregate the image and get the data and image correlated to the shape I want to learn about?

**Comment by LucaMarconato** [comment]
Crossref to the answer that I wrote here: https://discourse.scverse.org/t/can-i-aggregate-images-and-data-by-shapes/1513/3. Closing for now.
