### ISSUE TITLE
Issue: slow update time element widget.

### ISSUE THREAD

**Issue by melonora** [scverse/napari-spatialdata#125]
When layers are being displayed and then switching coordinate systems, it takes a long time to update the element widget.

**Comment by LucaMarconato** [comment]
by contrast, the speed is very good in the `spatialdata` branch

**Comment by LucaMarconato** [comment]
I think it's due to this https://github.com/scverse/napari-spatialdata/blob/e1d308d16a8dcbb7b23de4473de08c1d698b7212/src/napari_spatialdata/_interactive.py#L239

We should pass a list of images to `add_image()` to make use of the multiscale representation.
