### ISSUE TITLE
Problem with switching visibility of coordinate systems

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#130]
Noticed a bug, reporting it quickly here.

I had a `SpatialData` with two images, `a` and `b`. Each image is mapped to two coordinate system `sys1` and `sys2`. The mapping is as follows:

- `a -> sys1`: identity
- `b -> sys1`: identity
- `a -> sys2`: any affine/scale/translation
- `b -> sys2`: any affine/scale/translation

In the viewer I do the following:
1. select `sys1`. Then I open the elements `a` and `b`.
2. select `sys2`. Then I open the elements `a` and `b`.
3. click to `sys1`. The layers visibility changes as expected (the transformed layers disappear)
4. click to `sys2`. **Nothing happens**. Expected is that the untransformed layers disappear and the transformed ones appear.

**Comment by melonora** [comment]
hmm I will check reproducing this later, but in any case we should move of applying a transform when switching coordinate systems so layers do not have to be reopened when switching coordinate systems. Do you agree?

I first wanted to have #120 in before doing this.

**Comment by LucaMarconato** [comment]
Yes, I think that's a better approach.

**Comment by LucaMarconato** [comment]
Correct, I verified and with the new approach the issue is not relevant anymore because the affine transformation of the images is updated in-place.
