### ISSUE TITLE
Non-RGB multichannels can be 3

### ISSUE THREAD

**Issue by aeisenbarth** [scverse/napari-spatialdata#150]
In pull request #115 for issue #66, a logic was implemented that converts multichannels to RGB if they are three.

In our use case, we have non-RGB channels, that can be 2, 4 or sometimes 3. The problem is that independent channels have very different value ranges and are not necessarily normalized, so that one RGB component is dominating. Furthermore, the visualization does not represent physical colors and can be misleading to the viewer.

![image](https://github.com/scverse/napari-spatialdata/assets/54448967/c796bda4-91ca-4b3d-b3a7-d8b3b5be80b4)

Is there a way to set up the SpatialData object to explicitly use colors from the metadata, and avoid interpretation as RGB?

I think Napari's logic is that `c` must be 3 and additionally the order provided by the user must be `yxc` to interpret an image as RGB.

**Comment by melonora** [comment]
Hi @aeisenbarth, at the moment it is the case that in case of 3 or 4 channels it is interpreted as RGB. I will implement an RGB argument similar to napari which should support your usecase.

**Comment by aeisenbarth** [comment]
I also found that in [_get_affine_for_images_labels](https://github.com/scverse/napari-spatialdata/blob/2590e1e8191091820478b470ef7aee8bfd322be8/src/napari_spatialdata/interactive.py#L120) (on branch spatialdata), we could also inspect channel names, if these are always available for true RGB images:
```python
{"r", "g", "b"} <= set(element["scale0"].coords.indexes["c"]) # for MultiscaleSpatialImage
```

**Comment by melonora** [comment]
These are not always available for true RGB images as far as I know. @LucaMarconato could you pitch in?

**Comment by LucaMarconato** [comment]
Thanks @aeisenbarth for reporting. I think that a quick workaround would be to implement the RGB argument mentioned by @melonora to mimic the napari's functionality. I also think that the clean solution would be to rely exclusively on channel name and ensure that they are always present when needed by:
1) add an argument `rgb: bool = None` in `ImageModel.parse()` to give a convenience function to the user to set the channel names. The behavior could be to set the names to `r`, `g`, `b` based on the number of channels when `rgb` is `None` or is `True`, but also to give a printed log to the user when `rgb` is `None`.
2) modifying the readers of spatialdata-io to use the `rgb=True` parameter when calling `ImageModel.parse()`.

**Comment by aeisenbarth** [comment]
I could do a PR for this.

I didn't find `ImageModel`, I assume `Image2DModel` (and 3D). The `parse` function is implemented in `RasterSchema`, so instead of copying the full signature to `Image2DModel` just to add one argument, I could add the `rgb` argument in RasterSchema (but it is also used by labels) or even better in `to_spatial_image` because there is also `c_coord`.

If `rgb` is None and there are 3 or 4 channels and `c_coords` is not explicitly passed, I would set it to True and log it. Then if `rgb` is True, I would set `c_coords` to `["r", "g", "b"]` (or `"a"`).
In `napari-spatialdata`, change the RGB detection based on names in `c_coords`.

The behavior would be unchanged for `rgb=None`, I don't know the formats in `spatialdata-io` well enough to know whether its right to interprete them as RGB?

**Comment by melonora** [comment]
some like visium would be RGB

**Comment by aeisenbarth** [comment]
Ok, so I propse now four PRs: https://github.com/spatial-image/spatial-image/pull/21, https://github.com/scverse/spatialdata/pull/342, [napari-spatialdata#153](https://github.com/scverse/napari-spatialdata/pull/153), https://github.com/scverse/spatialdata-io/pull/78

**Comment by LucaMarconato** [comment]
Thanks a lot for the contribution @aeisenbarth, amazing work! I have merged the PR in spatialdata, but before the others I would wait for the one in `spatial-image` as otherwise it would probably lead to problems. But looks really good to me!

**Comment by aeisenbarth** [comment]
Images are still bright red.

Can someone please have a look at the PRs? The issue will continue to persist as long as not all of them are merged.

So far, only one is merged and these are still open:
- https://github.com/spatial-image/spatial-image/pull/21
- https://github.com/scverse/napari-spatialdata/pull/153
- https://github.com/scverse/spatialdata-io/pull/78

spatialdata-plot has this problem, I'll have to check whether it also needs a PR.

**Comment by melonora** [comment]
yes we are at a hackathon currently, sorry for it taking so long!

**Comment by thewtex** [comment]
>  I asked @thewtex whether the PR in spatial-image can be merged.

Yes! Done and released.

**Comment by melonora** [comment]
Thanks!

**Comment by LucaMarconato** [comment]
Thanks! Now the only blocker is this PR: https://github.com/scverse/spatialdata/issues/395, I will try to address it soon.

**Comment by melonora** [comment]
I will take it up this evening

**Comment by LucaMarconato** [comment]
Thanksss! I'd expect that change to break many parts across all the repos, we can also split the work. Let's sync via Zulip.

**Comment by melonora** [comment]
@aeisenbarth just as an update, I opened https://github.com/scverse/spatialdata/pull/587 to change to the new version of `SpatialImage` that includes your PR there. Waiting for it to be reviewed before continueing.

**Comment by LucaMarconato** [comment]
@aeisenbarth this issue can be closed right?

**Comment by LucaMarconato** [comment]
Tested, it works. Thanks @aeisenbarth @melonora.
