### ISSUE TITLE
Can't display labels when no table is present

### ISSUE THREAD

**Issue by timtreis** [scverse/napari-spatialdata#157]
When opening the raccoon data in the current main branch, I can't open the segmentation layer and get the following output:

<img width="757" alt="image" src="https://github.com/scverse/napari-spatialdata/assets/12818242/7f2411d5-4a02-44ad-ba16-2436a940b4cb">

**Comment by melonora** [comment]
Thanks for reporting! I will have a look

**Comment by LucaMarconato** [comment]
I have tested this and the problem doesn't occur anymore. Closing this issue.

Nevertheless, I have noticed that if one tries to plot on of the annotations (say `channel_0_sum`), when the labels are not selected, one gets an error. I reported this here: https://github.com/scverse/napari-spatialdata/issues/164
