### ISSUE TITLE
Add public API to change coordinate system and related tests

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#158]
@melonora, writing down the points from our discussion.

The method `Interactive.add_element()` was introduced for programmatic use, to open napari in a ci environment and take screenshot to compare with ground truth one.

The elements can be added to coordinate systems, in that case the expected behavior would be for those elements to be added without inducing a coordinate system change.
- [x] a test for this should be added

- [x] It would be nice, in addition to this, to have a public API to induce a coordinate system change.
- [x] A test for this should also be added.

**Comment by melonora** [comment]
This should be closed with [#169](https://github.com/scverse/napari-spatialdata/pull/169) and [#170](https://github.com/scverse/napari-spatialdata/pull/170).
