### ISSUE TITLE
Save back to zarr

### ISSUE THREAD

**Issue by grst** [scverse/napari-spatialdata#160]
I am following the [landmark annotation tutorial](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/alignment_using_landmarks.html) to annotate points in a SpatialData object. 

However, I'm working on a remote system without a graphical user interface, so I can't use `Interactive()`. But I have napari available on my local machine and can open the `.zarr` files. 

This works reasonably well, however I don't seem to be able to save the modifications back to the zarr store such that I can use the annotations from my ipython session. Is this possible somehow? 

I believe this would also be very useful for scientists who don't use python to analyze data (e.g. pathologists). Like that I could provide them with a link to the zarr object and they could just annotate & save.

**Comment by melonora** [comment]
I opened #168 as a draft which has a dependency on a PR in SpatialData.

**Comment by LucaMarconato** [comment]
@grst hi, the saving functionality has been ported from the old branch that we used for the notebooks; you can used it from the linked PR, which is ready for review and will be merged this week.

The new implementation is more stable, has more tests and most importantly is more transparent when dealing with multiple `SpatialData` objects, by allowing the user to choose where to save the annotations.
