### ISSUE TITLE
The plot should be invariant against reordering of the table rows

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#181]
As it can be observed when running this code: https://github.com/scverse/napari-spatialdata/pull/175#issuecomment-1793767601

Shuffling the rows of the table changes the plots, while it should not. This happens because currently `instance_key` is ignored. A solution is to call the function `match_table_to_element()` to match the rows of the table to the geometries to display https://github.com/scverse/spatialdata/blob/bf3377fd36f94ef51a233ae71312b1c28e978e6e/src/spatialdata/_core/query/relational_query.py#L134.

Weirdly, the bug appears only for labels and not for circles. The reason is probably the use of the fragile mechanism around `_labels_key` in `_model.py`, reason for which I suggest to first clean up the codebase around the model as described here https://github.com/scverse/napari-spatialdata/issues/180, and then address the current issue.

**Comment by melonora** [comment]
Based on #208 I will close this.
