### ISSUE TITLE
PyPi release issue

### ISSUE THREAD

**Issue by goanpeca** [scverse/napari-spatialdata#19]
Hi @giovp

We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

In the process of creating the conda recipe at https://github.com/conda-forge/staged-recipes/pull/19589, we noticed that the release on PyPi is tagged with `0.0.0`

https://pypi.org/project/napari-spatialdata/

<img width="1127" alt="Screen Shot 2022-08-03 at 3 24 58 PM" src="https://user-images.githubusercontent.com/3627835/182704853-6ef76dcb-e766-4557-82fa-db9d15ab2357.png">

@giovp do you think it would be possible to fix this, by making a new release that correctly uploads to the 0.1.0 version?

Cheers!

**Comment by giovp** [comment]
hi @goanpeca thanks a lot for the help with this and apology for my late reply. It should be fixed now and the pypi version should be correctly tagged with `0.1.0`
