### ISSUE TITLE
Segfault in test_points_inside_triangles

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#23]
I am trying running the tests with `tox` and I am getting a segmentation fault on the test `test_points_inside_triangles`. Currently I have only `python3.9` installed so the tests for `python3.8` and `python3.10` are skipped.
Have you encountered this problem before?

![image](https://user-images.githubusercontent.com/2664412/187460055-40cba329-2b03-44df-a4b5-50ca31b2dd6f.png)

**Comment by giovp** [comment]
hi super late, this is probably due to numba? which system was it run on (e.g. was it an apple M1, windows?)

**Comment by LucaMarconato** [comment]
It was an Apple with Intel processor, anyway I think now that function got removed, or at least the error disappeared.
