### ISSUE TITLE
Points disappear when the center is out of the view

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#24]
As you can see in the GIF, a point disappears from the view when its center is outside the view. Is this a bug/behavior of napari or something specific to napari-spatialdata? In the first case I would open a issue in the napari repo.

![out](https://user-images.githubusercontent.com/2664412/188676256-33119a9c-db33-463b-ba13-709a56ba84bd.gif)

**Comment by LucaMarconato** [comment]
I opened a issue in the napari imagesc forum https://forum.image.sc/t/points-disappear-when-the-center-is-out-of-view/72202

**Comment by giovp** [comment]
I'll close this as it seems something related to machine specifics
