### ISSUE TITLE
napari xcb plugin error

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/napari-spatialdata#258]
Hi,
When I use napari-spatialdata, the following error occurred:
![image](https://github.com/scverse/napari-spatialdata/assets/29703450/f59d5eee-8660-486d-84ac-64f431163cf3)
How to fix it ?

**Comment by melonora** [comment]
Hi do I correctly understand that you are trying to use the plugin on the cluster?

**Comment by wangjiawen2013** [comment]
Yes, I am using napari-spatialdata on Centos7 server

**Comment by melonora** [comment]
In that case it has to do with the required drivers for running napari. Please see this thread: https://forum.image.sc/t/remote-viewing-options/97355. We understand that it may be difficult to set this up. Another option is to set up a virtual machine on the cluster. This would alleviate the issue regarding drivers, but would probably require you to get in touch with your IT team.

**Comment by wangjiawen2013** [comment]
It's really a bit tricky. Is napari-spatialdata designed for windows/mac desktop or linux server ?

**Comment by melonora** [comment]
It is designed for windows / mac / Linux desktop as it is based on napari which due to opengl drivers etc runs on desktops. That being said some made it work with the xpra docker container mentioned in the link

**Comment by wangjiawen2013** [comment]
Thank, I'll install it on my windows desktop.

**Comment by melonora** [comment]
ok let us know if you encounter any other issues or have some feedback!

**Comment by LucaMarconato** [comment]
Thanks @melonora for giving extensive answers. @wangjiawen2013 one additional details: the behavior you observed would occur also if running the command `napari` from the terminal, even without using the `napari-spatialdata` plugins. If the problem keeps occurring I would also consider searching for solutions on the [napari issue tracker page](https://github.com/napari/napari/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen). Anyway feel also free to continue the conversation here if needed.
