### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by methornton** [scverse/napari-spatialdata#298]
Hello!

I've installed napari-spatialdata in its own conda env. I've installed and updated every package and all of the ubuntu libs suggested have also been installed. They were already the newest.

`sudo apt-get install -y libegl1 libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 x11-utils libxcb-cursor0 libopengl0 libegl1-mesa`

```
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from spatialdata import SpatialData

In [2]: sdata = SpatialData.read("/home/met/Data/Baldauf/18Aug24/ROI1/CHLA_HuPlacenta_Roi1Results.z
   ...: arr")
/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/anndata/_core/aligned_df.py:67: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [3]: from napari_spatialdata import Interactive

In [4]: Interactive(sdata)
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

```
Any information that you can give me is greatly appreciated. Thank you!

**Comment by Czaki** [comment]
Hi. You may take a look at this discussion https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/Crash.20when.20installing.20a.20new.20plugin/near/411416111

If you to not find solution there, please try to localize `libqxcb.so` and paste the output of `ldd` on this file.

**Comment by LucaMarconato** [comment]
Thanks @Czaki for the reply! @methornton please notice that a quicker way to reproduce is to run the `napari` command from the terminal as the problem appears to be with loading graphical interfaces in general and not specific to the `napari-spatialdata` plugin.

**Comment by methornton** [comment]
@Czaki Thank you!  I have been reading through the post. I really appreciate your help.

Here is the the output of find
```
/opt/zoom/Qt/plugins/platforms/libqxcb.so
/home/met/.local/lib/python3.10/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so
/home/met/anaconda3/plugins/platforms/libqxcb.so
/home/met/anaconda3/envs/napari-env/plugins/platforms/libqxcb.so
/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so
/home/met/anaconda3/pkgs/qt-main-5.15.2-h327a75a_7/plugins/platforms/libqxcb.so
/home/met/anaconda3/pkgs/qt-5.9.7-h5867ecd_1/plugins/platforms/libqxcb.so
/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
```
Here is the ldd of .local/lib/python3.10/site-packages
```
ldd /home/met/.local/lib/python3.10/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so
	linux-vdso.so.1 (0x00007fffbdb49000)
	libQt5XcbQpa.so.5 => /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 (0x00007eb4f19fd000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007eb4f19b3000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007eb4f18eb000)
	libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007eb4f18cf000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007eb4f0e00000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007eb4f1839000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007eb4f0800000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007eb4f1579000)
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007eb4f1834000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007eb4f182f000)
	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007eb4f1828000)
	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007eb4f1820000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007eb4f181b000)
	libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007eb4f1816000)
	libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007eb4f1566000)
	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007eb4f180f000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007eb4f1557000)
	libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007eb4f1808000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007eb4f154d000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007eb4f1543000)
	libxcb-xinerama.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xinerama.so.0 (0x00007eb4f153e000)
	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007eb4f1520000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007eb4f14f6000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007eb4f14e1000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007eb4f06c0000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007eb4f0df5000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007eb4f0dd8000)
	libxkbcommon-x11.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007eb4f0dcd000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007eb4f0d86000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007eb4f0d81000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007eb4f0400000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007eb4f0319000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007eb4f0d61000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007eb4f0000000)
	libxcb-xinput.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xinput.so.0 (0x00007eb4f069c000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007eb4f068f000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007eb4efec6000)
	libexpat.so.1 => /usr/lib/x86_64-linux-gnu/libexpat.so.1 (0x00007eb4f065e000)
	libuuid.so.1 => /usr/lib/x86_64-linux-gnu/libuuid.so.1 (0x00007eb4f0655000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007eb4f02de000)
	libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007eb4f0647000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007eb4efdf7000)
	libmd4c.so.0 => /usr/lib/x86_64-linux-gnu/libmd4c.so.0 (0x00007eb4f0635000)
	libdbus-1.so.3 => /usr/lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007eb4f0290000)
	libdouble-conversion.so.3 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007eb4f027b000)
	libicui18n.so.70 => /usr/lib/x86_64-linux-gnu/libicui18n.so.70 (0x00007eb4efa00000)
	libicuuc.so.70 => /usr/lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007eb4ef805000)
	libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007eb4efd6d000)
	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007eb4ef736000)
	/lib64/ld-linux-x86-64.so.2 (0x00007eb4f1b7a000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007eb4ef67e000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007eb4f0247000)
	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007eb4f023e000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007eb4f0238000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007eb4f0230000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007eb4efd55000)
	libpcre.so.3 => /usr/lib/x86_64-linux-gnu/libpcre.so.3 (0x00007eb4ef608000)
	libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007eb4efd32000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007eb4ef5e1000)
	libsystemd.so.0 => /usr/lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007eb4ef51a000)
	libicudata.so.70 => /usr/lib/x86_64-linux-gnu/libicudata.so.70 (0x00007eb4ed800000)
	libmd.so.0 => /usr/lib/x86_64-linux-gnu/libmd.so.0 (0x00007eb4ef50d000)
	liblzma.so.5 => /usr/lib/x86_64-linux-gnu/liblzma.so.5 (0x00007eb4ef4e2000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007eb4ef4c2000)
	libcap.so.2 => /usr/lib/x86_64-linux-gnu/libcap.so.2 (0x00007eb4ef4b7000)
	libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007eb4ed6c2000)
	libgpg-error.so.0 => /usr/lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007eb4ef491000)

```
I installed a conda env for napari using python3.9 maybe that was a bad idea?

Here is my LD_LIBRARY_PATH
```
echo $LD_LIBRARY_PATH
:/usr/lib/x86_64-linux-gnu:/usr/local/lib/OracleJDK/jdk1.8.0_321//lib:/usr/lib/x86_64-linux-gnu/jack:/usr/local/lib/QuPath/QuPath-v0.5.1-Linux/QuPath/bin
```

**Comment by methornton** [comment]
@Czaki 
I ran the debug QT plugins and this was the output for libqxcb.so
```
10:39:30 : WARNING : MainThread : Found metadata in lib /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


WARNING: Got keys from plugin meta data ("xcb")
10:39:30 : WARNING : MainThread : Got keys from plugin meta data ("xcb")
WARNING: QFactoryLoader::QFactoryLoader() checking directory path "/home/met/anaconda3/envs/napari-env/bin/platforms" ...
10:39:30 : WARNING : MainThread : QFactoryLoader::QFactoryLoader() checking directory path "/home/met/anaconda3/envs/napari-env/bin/platforms" ...
WARNING: Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)
10:39:30 : WARNING : MainThread : Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)
WARNING: QLibraryPrivate::loadPlugin failed on "/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)"
10:39:30 : WARNING : MainThread : QLibraryPrivate::loadPlugin failed on "/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)"
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
10:39:30 : WARNING : MainThread : Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

10:39:30 : WARNING : MainThread : This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)10:39:30 : WARNING : MainThread : Found metadata in lib /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


WARNING: Got keys from plugin meta data ("xcb")
10:39:30 : WARNING : MainThread : Got keys from plugin meta data ("xcb")
WARNING: QFactoryLoader::QFactoryLoader() checking directory path "/home/met/anaconda3/envs/napari-env/bin/platforms" ...
10:39:30 : WARNING : MainThread : QFactoryLoader::QFactoryLoader() checking directory path "/home/met/anaconda3/envs/napari-env/bin/platforms" ...
WARNING: Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)
10:39:30 : WARNING : MainThread : Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)
WARNING: QLibraryPrivate::loadPlugin failed on "/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)"
10:39:30 : WARNING : MainThread : QLibraryPrivate::loadPlugin failed on "/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN23QPlatformVulkanInstance22presentAboutToBeQueuedEP7QWindow, version Qt_5_PRIVATE_API)"
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
10:39:30 : WARNING : MainThread : Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

10:39:30 : WARNING : MainThread : This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

Here is the ldd.
```

ldd ~/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so 
	linux-vdso.so.1 (0x00007fffa41a2000)
	libQt5XcbQpa.so.5 => /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 (0x00007ecb49d22000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007ecb49cd8000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007ecb49c10000)
	libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007ecb499e4000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007ecb49200000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007ecb49950000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007ecb48c00000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007ecb49179000)
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ecb49c09000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007ecb49c04000)
	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007ecb49949000)
	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007ecb49941000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007ecb4993c000)
	libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007ecb49937000)
	libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007ecb49924000)
	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007ecb4991d000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007ecb4990e000)
	libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007ecb49907000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007ecb498fd000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007ecb498f3000)
	libxcb-xinerama.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xinerama.so.0 (0x00007ecb498ee000)
	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007ecb48be2000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ecb48bb8000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007ecb49164000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007ecb48a78000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007ecb498e1000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007ecb48a5b000)
	libxkbcommon-x11.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007ecb48a50000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007ecb48a09000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007ecb4915f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ecb48600000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007ecb48922000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ecb48902000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007ecb48200000)
	libxcb-xinput.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xinput.so.0 (0x00007ecb488de000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007ecb488cf000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ecb484c6000)
	libexpat.so.1 => /usr/lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ecb4889e000)
	libuuid.so.1 => /usr/lib/x86_64-linux-gnu/libuuid.so.1 (0x00007ecb48895000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007ecb4885a000)
	libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007ecb4884a000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007ecb48131000)
	libmd4c.so.0 => /usr/lib/x86_64-linux-gnu/libmd4c.so.0 (0x00007ecb48838000)
	libdbus-1.so.3 => /usr/lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007ecb48478000)
	libdouble-conversion.so.3 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007ecb48463000)
	libicui18n.so.70 => /usr/lib/x86_64-linux-gnu/libicui18n.so.70 (0x00007ecb47e00000)
	libicuuc.so.70 => /usr/lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007ecb47c05000)
	libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007ecb47b7b000)
	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007ecb47aac000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ecb49e9f000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007ecb479f4000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007ecb4842f000)
	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007ecb479eb000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007ecb4882e000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ecb479e3000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ecb479cb000)
	libpcre.so.3 => /usr/lib/x86_64-linux-gnu/libpcre.so.3 (0x00007ecb47955000)
	libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007ecb47932000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007ecb4790b000)
	libsystemd.so.0 => /usr/lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007ecb47844000)
	libicudata.so.70 => /usr/lib/x86_64-linux-gnu/libicudata.so.70 (0x00007ecb45c00000)
	libmd.so.0 => /usr/lib/x86_64-linux-gnu/libmd.so.0 (0x00007ecb47837000)
	liblzma.so.5 => /usr/lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ecb45bd5000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007ecb45bb5000)
	libcap.so.2 => /usr/lib/x86_64-linux-gnu/libcap.so.2 (0x00007ecb4782c000)
	libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ecb45a77000)
	libgpg-error.so.0 => /usr/lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ecb45a51000)

```

```

**Comment by Czaki** [comment]
All libraries look installed. 
Maybe some element of `LD_LIBRARY_PATH` contain to old version of some library? 
What happen if you try to start `LD_LIBRARY_PATH="" napari`

**Comment by methornton** [comment]
@Czaki It went quite alot further. I think it was LD_LIBRARY_PATH 

WARNING: Got keys from plugin meta data ("ibus")
11:00:13 : WARNING : MainThread : Got keys from plugin meta data ("ibus")
WARNING: QFactoryLoader::QFactoryLoader() checking directory path "/home/met/anaconda3/envs/napari-env/bin/platforminputcontexts" ...
11:00:13 : WARNING : MainThread : QFactoryLoader::QFactoryLoader() checking directory path "/home/met/anaconda3/envs/napari-env/bin/platforminputcontexts" ...
WARNING: loaded library "/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
11:00:13 : WARNING : MainThread : loaded library "/home/met/anaconda3/envs/napari-env/lib/python3.9/site-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
WARNING: Cannot mix incompatible Qt library (5.15.14) with this library (5.15.2)
11:00:13 : WARNING : MainThread : Cannot mix incompatible Qt library (5.15.14) with this library (5.15.2)

**Comment by Czaki** [comment]
Yes. If you have any installation of Qt in your `LD_LIBRARY_PATH` the napari start will crash.

**Comment by methornton** [comment]
Thank you!! ![Screenshot from 2024-08-19 11-44-27](https://github.com/user-attachments/assets/61d05a60-30cb-46ca-9279-fa5062136fe7)
