### ISSUE TITLE
Sphinx documentation missing requirements

### ISSUE THREAD

**Issue by rahulbshrestha** [scverse/napari-spatialdata#49]
Trying to generate sphinx documentation with ```make html``` prompted the following packages as missing. 

1. sphinx_qt_documentation
2. sphinx-autodoc-typehints
3. sphinxcontrib-bibtex
4. sphinx-book-theme

For the top three, the error message was of the form:
```
Extension error:
Could not import extension sphinx_qt_documentation (exception: No module named 'sphinx_qt_documentation')
```

For the last one, the error message was: 
```
Theme error:
no theme named 'sphinx_book_theme' found (missing theme.conf?)
```

**Comment by giovp** [comment]
think this is now in `napari-spatialdata[doc]`
