### ISSUE TITLE
Set a reasonable upper bound of points that we want to render

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#55]
napari currently can't render more than X points. Find a reasonable value for X (probably something between 100K and 1M) and change the code to subset to this number of points (load only those in-memory from dask and show only them).

**Comment by timtreis** [comment]
- [ ] check if we can pass that number to the viewer? maybe config file? Or argument that potentially overwrites the default

**Comment by LucaMarconato** [comment]
The number is now 100000 and the subset is done correctly. For the moment I would keep it like this hardcoded.
