### ISSUE TITLE
RBG images are shown as multichannel images

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#66]
Images should be rendered with `rgb=True` when they have 3 channels.

**Comment by kevinyamauchi** [comment]
@giovp , @rahulbshrestha , @tothmarcella , would one of you be able to work on this?

**Comment by melonora** [comment]
I already have code for this too:) it was in #93 which was mostly a port from Luca's code on the spatialdata branch, but then with some utility functions.

**Comment by giovp** [comment]
@rahulbshrestha should have taken that and ported to another PR @rahulbshrestha could you comment here?

**Comment by rahulbshrestha** [comment]
yup, I put up a PR here based on Wouter's code: https://github.com/scverse/napari-spatialdata/pull/115

**Comment by melonora** [comment]
Completed with #115
