### ISSUE TITLE
Can't color circles by genes in visium dataset

### ISSUE THREAD

**Issue by kevinyamauchi** [scverse/napari-spatialdata#71]
Hello! I was trying the [ROI notebook](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/napari_rois.html). I can load the shapes, but when I open the "view" plugin from the plugin menu, I can't color the points.

![Screenshot 2023-05-11 at 15 18 29](https://github.com/scverse/napari-spatialdata/assets/1120672/b31516bf-5027-4ccd-b8bc-8668e5d8c89c)

**To reproduce**
1. launch the interactive viewer as specified in [ROI notebook](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/napari_rois.html)
2. open the "downscaled_lowres" coordinate system by clicking it in the "Coordinate System" list
3. load the shapes elements by double clicking them
4. Open the "View" plugin from the plugin menu
5. Click or double click any of the obs or genes. The circles do not change color. I also tried changing the slider for the colors and I didn't see any change

**Comment by kevinyamauchi** [comment]
Do you see the same thing, @giovp and @rahulbshrestha ? Or am I just doing something wrong?

**Comment by rahulbshrestha** [comment]
Closed by https://github.com/scverse/napari-spatialdata/pull/73.
