### ISSUE TITLE
Invalid update corner pixels when opening shapes layer

### ISSUE THREAD

**Issue by melonora** [scverse/napari-spatialdata#79]
When displaying an image from a test dataset and then opening a shapes layer a runtime warning is thrown `invalid value encountered in cast`. The error originates from `napari.layers.base.base.py` line 1632. I did not check yet whether the updated corner pixels of the canvas are valid or not. This occurred with multiple datasets on the main branch.

## Steps to reproduce
```
sdata = SpatialData.read(<path.zarr>)
interactive = Interactive(sdata)
interactive.run()
```

Make any image visible and then click on the shapes button to create a shapes layer.

**Comment by melonora** [comment]
ok so for this one an update. I saw @VictorDidier having the same issue today when working with napari and asked him to open a bug report [#5909](https://github.com/napari/napari/issues/5909). It can be that it is fixed with [#5432](https://github.com/napari/napari/pull/5423) and is currently not an issue on main anymore. It is flagged for release 0.4.18 later this month so we can come back to this issue after that release.

**Comment by rahulbshrestha** [comment]
@melonora is this napari related? can close this issue if it is.

**Comment by melonora** [comment]
Closed as it is napari related
