### ISSUE TITLE
Support saving shapes / points when visualizing multiple spatialdata objects at once

### ISSUE THREAD

**Issue by melonora** [scverse/napari-spatialdata#83]
Currently on main it is not supported to visualize multiple spatialdata objects, but this will be supported in the future. Once supported on the main branch, it should be supported to save shapes / points to multiple spatialdata objects at the same time.

**Comment by LucaMarconato** [comment]
To keep track of the multiple spatialdata objects issue: https://github.com/scverse/napari-spatialdata/issues/112
