### ISSUE TITLE
build few useful dataset as examples

### ISSUE THREAD

**Issue by giovp** [scverse/napari-spatialdata#9]
https://squidpy.readthedocs.io/en/latest/api.html

**Comment by ivirshup** [comment]
`bento.datasets.load_dataset("merfish")` could be good here. It has points and shapely polygons.

**Comment by giovp** [comment]
> `bento.datasets.load_dataset("merfish")` could be good here. It has points and shapely polygons.

update, there is no image, shoudl change logic for only points...
